# Generated by Django 4.0.4 on 2022-06-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_id', models.IntegerField()),
                ('cust_id', models.IntegerField()),
            ],
            options={
                'db_table': 'idgen',
            },
        ),
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('cust_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=90)),
                ('street', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('pin_code', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
        migrations.CreateModel(
            name='tbl_stall',
            fields=[
                ('stall_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('stall_number', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=90)),
                ('descripion', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_stall',
            },
        ),
    ]
