# Generated by Django 4.0.4 on 2022-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_restaurent',
            fields=[
                ('rest_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('rest_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('pin_code', models.CharField(max_length=90)),
                ('particulers', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
                ('rm_name', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_restaurent',
            },
        ),
        migrations.AddField(
            model_name='idgen',
            name='rest_id',
            field=models.IntegerField(default=344),
            preserve_default=False,
        ),
    ]
