# Generated by Django 4.0.4 on 2022-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbl_restaurent_idgen_rest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('user_name', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('cat', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
    ]
