# Generated by Django 4.0.4 on 2022-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_menu',
            fields=[
                ('menu_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('rest_id', models.CharField(max_length=30)),
                ('menu_name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('photo', models.CharField(max_length=90)),
                ('unit', models.CharField(max_length=90)),
                ('quantity', models.CharField(max_length=90)),
                ('price', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_menu',
            },
        ),
        migrations.AddField(
            model_name='idgen',
            name='menu_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
