# Generated by Django 4.0.4 on 2022-06-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_menu_idgen_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_menu',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent'),
        ),
    ]
