# Generated by Django 4.0.4 on 2022-07-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tbl_menu_rest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_table',
            fields=[
                ('table_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('table_no', models.CharField(max_length=90)),
                ('numberof_chair', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent')),
            ],
            options={
                'db_table': 'tbl_table',
            },
        ),
    ]
