# Generated by Django 4.0.4 on 2022-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tbl_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='table_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
