# Generated by Django 4.0.4 on 2022-07-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_idgen_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='review_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('review', models.CharField(max_length=90)),
                ('review_date', models.CharField(max_length=90)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_customer')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
