# Generated by Django 4.0.4 on 2022-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_idgen_review_id_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='photo',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
