# Generated by Django 4.0.4 on 2022-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_idgen_emp_id_tbl_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employee',
            name='house_name',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_employee',
            name='name',
            field=models.CharField(default=3, max_length=90),
            preserve_default=False,
        ),
    ]
