# Generated by Django 4.0.4 on 2022-07-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_idgen_tbl_book_id_tbl_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='cust_orderid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_cust_order',
            fields=[
                ('cust_orderid', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('req_quantity', models.CharField(max_length=90)),
                ('amount', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_customer')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent')),
            ],
            options={
                'db_table': 'tbl_cust_order',
            },
        ),
    ]
