# Generated by Django 4.0.4 on 2022-07-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_tbl_cust_order_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='r_s_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_rest_stall',
            fields=[
                ('r_s_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent')),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_stall')),
            ],
            options={
                'db_table': 'tbl_rest_stall',
            },
        ),
    ]
