# Generated by Django 4.0.4 on 2022-07-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_idgen_r_s_id_tbl_rest_stall'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tablebooking',
            name='ds',
            field=models.CharField(default='s', max_length=90),
            preserve_default=False,
        ),
    ]
