# Generated by Django 4.0.4 on 2022-07-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tbl_tablebooking_ds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tablebooking',
            name='ds',
        ),
    ]
