# Generated by Django 4.0.4 on 2022-07-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_tbl_tablebooking_ds'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='appl_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_leave_application',
            fields=[
                ('appl_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('leave_appl_date', models.CharField(max_length=90)),
                ('leave_date', models.CharField(max_length=90)),
                ('no_of_days', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_employee')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_restaurent')),
            ],
            options={
                'db_table': 'tbl_leave_application',
            },
        ),
    ]
