# Generated by Django 4.0.4 on 2022-07-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_idgen_appl_id_tbl_leave_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='emp_duty_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_emp_duty',
            fields=[
                ('emp_duty_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('duty', models.CharField(max_length=90)),
                ('allotment_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_employee')),
            ],
            options={
                'db_table': 'tbl_emp_duty',
            },
        ),
    ]
