# Generated by Django 4.0.4 on 2022-07-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_idgen_emp_duty_id_tbl_emp_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='payment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('payment_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('payment_type', models.CharField(max_length=90)),
                ('bank', models.CharField(max_length=90)),
                ('ifsc', models.CharField(max_length=90)),
                ('amount', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('cust_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_cust_order')),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
    ]
