# Generated by Django 4.0.4 on 2022-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_idgen_payment_id_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='account',
            field=models.CharField(default='26549876009', max_length=90),
            preserve_default=False,
        ),
    ]
