# Generated by Django 4.0.4 on 2022-05-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('o_id', models.IntegerField()),
            ],
            options={
                'db_table': 'idgen',
            },
        ),
        migrations.CreateModel(
            name='prdct',
            fields=[
                ('p_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.CharField(max_length=90)),
                ('p_pic', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'prdct',
            },
        ),
        migrations.CreateModel(
            name='odr',
            fields=[
                ('o_id', models.CharField(max_length=90, primary_key='True', serialize=False)),
                ('o_date', models.CharField(max_length=30)),
                ('o_qnty', models.CharField(max_length=30)),
                ('o_sts', models.CharField(max_length=30)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prdct')),
            ],
            options={
                'db_table': 'odr',
            },
        ),
    ]
