# Generated by Django 4.0.4 on 2022-05-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'stud',
            },
        ),
    ]
