# Generated by Django 4.0.4 on 2022-05-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
    ]
